##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.23.0] date: [Sat Aug 19 21:57:50 MSK 2017]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = SMController


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# source path
SOURCES_DIR =  \
FreeRTOS \
Drivers \
Drivers/HAL \
Drivers/CMSIS \
Drivers/MPU6050 \
User

# firmware library path
PERIFLIB_PATH = 

# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Drivers/HAL/Src/stm32f1xx_hal_uart.c \
Drivers/HAL/Src/stm32f1xx_hal_rcc_ex.c \
Drivers/HAL/Src/stm32f1xx_hal_pwr.c \
Drivers/HAL/Src/stm32f1xx_hal_gpio_ex.c \
Drivers/HAL/Src/stm32f1xx_hal_gpio.c \
Drivers/HAL/Src/stm32f1xx_hal.c \
Drivers/HAL/Src/stm32f1xx_hal_flash.c \
Drivers/HAL/Src/stm32f1xx_hal_rcc.c \
Drivers/HAL/Src/stm32f1xx_hal_i2c.c \
Drivers/HAL/Src/stm32f1xx_hal_tim.c \
Drivers/HAL/Src/stm32f1xx_hal_cortex.c \
Drivers/HAL/Src/stm32f1xx_hal_tim_ex.c \
Drivers/HAL/Src/stm32f1xx_hal_flash_ex.c \
Drivers/HAL/Src/stm32f1xx_hal_dma.c \
Drivers/Perifeeral/Src/usart.c \
Drivers/Perifeeral/Src/i2c.c \
Drivers/Perifeeral/Src/gpio.c \
Drivers/MPU6050/Src/mpu6050.c \
User/Src/system_stm32f1xx.c \
User/Src/main.c \
User/Src/freertos.c \
User/Src/stm32f1xx_it.c \
User/Src/stm32f1xx_hal_msp.c \
User/Src/task_inputs.c \
User/task_turnlights.c \
FreeRTOS/Src/croutine.c \
FreeRTOS/Src/port.c \
FreeRTOS/Src/queue.c \
FreeRTOS/Src/tasks.c \
FreeRTOS/Src/list.c \
FreeRTOS/Src/event_groups.c \
FreeRTOS/Src/CMSIS_RTOS/cmsis_os.c \
FreeRTOS/Src/timers.c \
FreeRTOS/Src/MemMang/heap_1.c \

# ASM sources
ASM_SOURCES =  \
startup_stm32f103xb.s


######################################
# firmware library
######################################
PERIFLIB_SOURCES = 


#######################################
# binaries
#######################################
BINPATH = 
PREFIX = arm-none-eabi-
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
AR = $(PREFIX)ar
SZ = $(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F103xB


# AS includes
AS_INCLUDES =  \
-IInc

# C includes
C_INCLUDES =  \
-IUser/Inc \
-IDrivers/HAL/Inc \
-IDrivers/HAL/Inc/Legacy \
-IFreeRTOS/Inc \
-IDrivers/CMSIS/Device/ST/STM32F1xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/MPU6050/Inc \
-IDrivers/Periferal/Inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F103C8Tx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

# *** EOF ***
