#ifndef PLATFOORM_CONFIG_H
#define PLATFOORM_CONFIG_H

/* Definitions */
#define UART1_SPEED 115200
#define UART2_SPEED 115200
#define UART3_SPEED 115200

#define GPIO_PIN_I_TURN_L   GPIO_PIN_13
#define GPIO_PIN_I_TURN_R   GPIO_PIN_12
#define GPIO_PIN_I_STOP     GPIO_PIN_14
#define GPIO_PIN_I_LIGHT    GPIO_PIN_15

#define GPIO_PIN_O_TURN_L   GPIO_PIN_3
#define GPIO_PIN_O_TURN_R   GPIO_PIN_9
#define GPIO_PIN_O_STOP     GPIO_PIN_4
#define GPIO_PIN_O_BRAIN_ON GPIO_PIN_8
#define GPIO_PIN_O_LIGHT    GPIO_PIN_5


#endif // PLATFOORM_CONFIG_H
